### ISSUE TITLE
Graphics don't display properly (Avogadro 2 on Linux, displayed on XQuartz)

### ISSUE THREAD

**Issue by stmilne** [OpenChemistry/avogadroapp#108]
**Avogadro version:**
Installed from "yum install", on a Linux cluster running CentOS 7:

 - Avogadrolibs:   avogadro2-libs.x86_64 0:1.90.0-12.el7
 - Qt:      qt.x86_64 1:4.8.7-3.el7_6

**Desktop version:**
Desktop machine is the graphics client, displaying windows:

 - OS:  Mac OS X 10.12.16
 - XQuartz 2.7.11
 - Late 2011 MacBook Pro, with stock graphics card (Intel HD Graphics 3000)

**Describe the bug**

Window that displays molecules is messed up, with pieces of other desktop windows randomly scattered inside.

**To Reproduce**

Window is immediately messed up on launch, rather than black.

**Screenshots**
![Screen Shot 2020-02-04 at 3 46 47 PM](https://user-images.githubusercontent.com/60672488/73790342-523e2300-476e-11ea-8c46-e7d56f19f467.png)

**Comment by ghutchis** [comment]
I guess my first question is why you installed this way, rather than the Mac build?

My guess is that there's an issue with XQuartz and OpenGL contexts - it seems to be grabbing something from a webpage?

**Comment by stmilne** [comment]
Because 1) I found Avogadro 2 to be really crashy and buggy on the Mac, and 2) the intended workflow is to build and examine configurations for quantum chemistry codes on our cluster. 

 I was hoping Avo 2 would be better behaved on Linux.  In contrast, Avogadro 1.2 is quite usable on both platforms, whereas I find Avo 2 unusable.

**Comment by ghutchis** [comment]
send me an e-mail and let's talk. I've never been able to crash Avo2 on my Mac, so  I'm curious.

**Comment by stmilne** [comment]
Goeff — Thanks for your reply.   I re-examined the Mac version of Avo 2 this morning, and reminded myself why it is unusable for me in its present form.
I didn’t get Avo 2 to crash, but functionally it is a big step backwards from Avo 1.2:

1)  I can’t clean up structures with energy minimization (there’s no button on the toolbar, and menu item Extension / OpenBabel / Optimize Geometry doesn’t work).
This is basically fatal, since e.g., building an alkane gives an incorrect C-C bond length of 1.07A, with atoms so close together it’s difficult to select bonds.

2) There’s no “Add Fragment” menu item, and Build / Insert / SMILES… doesn’t work.  It seems there’s a Plugin Downloader (under Extensions) with a plugin for structures, 
but the downloader doesn’t do anything when I select plugins and press the button.

3) There’s no Properties windows for Atoms / Bonds / Angles / Torsions, so no way to edit these numbers to precise values.

4) Avo 2 cannot read or write pdb files.  PDB is the “lingua franca” of molecular structures.  This is also a fatal shortcoming for me.

It appears that Avo 2 is a ground-up rewrite of Avo 1.2, with a different toolbox for the GUI, faster response to menu choices, etc.  That’s nice — 
but if Avo 2 is not functionally equivalent to Avo 1.2, then those advantages are not helpful.

Scott Milner
William H. Joyce Professor
The Pennsylvania State University
Department of Chemical Engineering
204 CBE Building
University Park, PA 16802
(814) 863-9355
stm9@psu.edu

**Comment by drew-parsons** [comment]
@stmilne Hi Scott, avogadro2 v1.9.4 now addresses the first two problems you raised. Geometry optimization is now in Extensions->Open Babel->Optimize Geometry (Ctrl-Alt-O).  Fragments can be added via Build-Insert-Fragment.

Insert fragments with Smiles doesn't work for me either (the new Insert-Fragment is a separate function), and pdb files don't load for me.

**Comment by ghutchis** [comment]
@drew-parsons - please file an issue about Insert SMILES. As far as reading PDB files, that should be fixed by a recent avogadrolibs patch (https://github.com/OpenChemistry/avogadrolibs/pull/647)

My guess is that Scott will be better served by releases near the end of the summer. 😄

**Comment by drew-parsons** [comment]
Thanks Geoff, it's a good summer :)  Your PR#647 does indeed fix pdb file loading.

I'll check SMILES documentation and then file a bug if I still can't get it to import molecules.

**Comment by drew-parsons** [comment]
I filed a SMILES bug at https://github.com/OpenChemistry/avogadrolibs/issues/657

**Comment by ghutchis** [comment]
@stmilne - I'm going to close this bug. While I understand what features you want, it's unrelated to this redraw bug. (Which I can't reproduce on my Mac with current versions.)

If you'd like to try a nightly build, it's here, although it does not yet have the property tables right now: https://nightly.link/OpenChemistry/avogadrolibs/workflows/build_cmake/master/macOS.dmg.zip

(OTOH, you may be interested in some of the new Python command options for polymer building...)
